<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="XamlInternalException.xml" source-language="en-US" target-language="ru-RU">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac50729fa9645baf6a20d37770d139f103712c6612f.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">0729fa9645baf6a20d37770d139f103712c6612f</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Xaml.XamlInternalException">
          <source>The exception that is thrown for internal inconsistencies that occur during XAML reading and XAML writing.</source>
          <target state="translated">Исключение, которое создается в случаях внутренних несоответствий, возникающих во время чтения и записи XAML.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>This exception is usually thrown only when some aspect of the XAML reader or XAML writer system was extended by your code, and inconsistencies or implementation problems occurred that were passed on to the .NET Framework XAML Services system code.</source>
          <target state="translated">Это исключение обычно вызывается только в том случае, когда некоторые аспекты средства чтения XAML или системы средство записи XAML была расширена в коде, и несоответствия или проблемы реализации возникла, переданные системного кода служб XAML .NET Framework.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>Exceptions that might originate from third parties, such as parsing XAML and encountering errors in the XAML, should not throw <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph>, and should instead throw other exceptions such as <ph id="ph2">&lt;xref:System.Xaml.XamlParseException&gt;</ph> or <ph id="ph3">&lt;xref:System.Xaml.XamlObjectWriterException&gt;</ph>.</source>
          <target state="translated">Исключения, которые может быть создано сторонних производителей, например, синтаксический анализ кода XAML и обнаружения ошибок в XAML-ФАЙЛЕ, не должны вызывать <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph>и вместо этого должны вызывать другие исключения например <ph id="ph2">&lt;xref:System.Xaml.XamlParseException&gt;</ph> или <ph id="ph3">&lt;xref:System.Xaml.XamlObjectWriterException&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>If you are writing code that extends .NET Framework XAML Services, in particular, if you are writing code for a XAML reader or XAML writer implementation, you should maintain this distinction between <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph> and the other XAML-related exceptions.</source>
          <target state="translated">Если вы пишете код, который расширяет возможности служб XAML .NET Framework, в частности, при написании кода для средства чтения XAML или реализацию модуля записи XAML, необходимо поддерживать это различие между <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph> и другие исключения, связанные с XAML.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>Your code should only throw <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph> in cases where further extension of your class violates some design principle or implementation pattern that your callable code defines.</source>
          <target state="translated">Код создается только <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph> в случаях, когда это нарушает некоторые принцип или реализации шаблона разработки, вызываемых код определяет дальнейшее расширение класса.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>Your code should throw other XAML-specific exceptions for exception cases where your XAML reader or XAML writer implementation is used without extension and is used to load third-party XAML, third-party XAML schema context, and so on.</source>
          <target state="translated">Код должен вызывать другие исключения, связанные с XAML для исключения случаев, когда средства чтения или записи реализации XAML используется без расширения и используется для загрузки XAML сторонних разработчиков, стороннего контекста схемы XAML и т. д.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" uid="T:System.Xaml.XamlInternalException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class.</source>
          <target state="translated">Инициализирует новый экземпляр класса <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class with a system-supplied message that describes the error.</source>
          <target state="translated">Инициализирует новый экземпляр класса <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> с системным сообщением, содержащим описание ошибки.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String)">
          <source>The message that describes the exception.</source>
          <target state="translated">Сообщение с описанием исключения.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class with a specified message that describes the error.</source>
          <target state="translated">Инициализирует новый экземпляр класса <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> с использованием заданного сообщения, содержащего описание ошибки.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The object that holds the serialized object data.</source>
          <target state="translated">Объект, содержащий сериализованные данные объекта.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The contextual information about the source or destination.</source>
          <target state="translated">Контекстные сведения об источнике или назначении.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class with serialized data.</source>
          <target state="translated">Инициализирует новый экземпляр класса <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> с сериализованными данными.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)">
          <source>The message that describes the exception.</source>
          <target state="translated">Сообщение с описанием исключения.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">Исключение, которое является причиной текущего исключения.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)">
          <source>If the <bpt id="p1">&lt;c&gt;</bpt>innerException<ept id="p1">&lt;/c&gt;</ept> parameter is not <ph id="ph1">&lt;see langword="null" /&gt;</ph>, the current exception is raised in a <ph id="ph2">&lt;see langword="catch" /&gt;</ph> block that handles the inner exception.</source>
          <target state="translated">Если значение параметра <bpt id="p1">&lt;c&gt;</bpt>innerException<ept id="p1">&lt;/c&gt;</ept> не равно <ph id="ph1">&lt;see langword="null" /&gt;</ph>, текущее исключение возникает в блоке <ph id="ph2">&lt;see langword="catch" /&gt;</ph>, обрабатывающем внутреннее исключение.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">Инициализирует новый экземпляр класса <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> указанным сообщением об ошибке и ссылкой на внутреннее исключение, вызвавшее данное исключение.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>